spring.application.name=ProyectoSpringAndresCastellanos

spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=campus2023
spring.datasource.password=campus2023

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=miClaveSecretaParaLogiTrack2026Segura123456
jwt.expiration=1800000
